/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleCounter } from "./SimpleCounter";
export * as factories from "./factories";
export { SimpleCounter__factory } from "./factories/SimpleCounter__factory";
